controllers_HattStyle:
    resource:
        path: ../src/HattStyle/Controller/
        namespace: App\HattStyle\Controller
    type: attribute
controllers_Flatastic:
    resource:
        path: ../src/Flatastic/Controller/
        namespace: App\Flatastic\Controller
    type: attribute
